services:
    _defaults:
        autoconfigure: true

    marke_postit.listener.generate_page:
        class: Marke\PostItBundle\EventListener\GeneratePageListener
        arguments:
            - '@contao.security.token_checker'
